### ISSUE TITLE
Add configurable file support

### ISSUE THREAD

**Issue by lawrencegripper** [davidlday/vscode-languagetool-linter#306]
First up, thanks for the extension it's awesome.

**Is your feature request related to a problem? Please describe.**
I'd like to be able to add additional file extension to those supported by the extension, for example `.txt`.

**Describe the solution you'd like**
If you're happy for me to I'd like to submit a PR which updated [this code](https://github.com/davidlday/vscode-languagetool-linter/blob/7ea7b44c88b06ad06165391f21eb657b4e0f53c0/src/Constants.ts#L35) to pull from a VSCode setting `languageToolLinter.supportedFiles = ['.txt', '.erb']` or similar.

**Describe alternatives you've considered**
I could add these in statically but I think users would likely want to be able to configure these for their own setups.

**Comment by davidlday** [comment]
Thanks for the suggestion and the offer of a PR. There is a feature that allows the user to identify which Language IDs should be linted as if they were `plaintext`, which I think accomplishes the same goal:

![image](https://user-images.githubusercontent.com/1132144/121741556-b0021e00-cacc-11eb-8273-1571c9be1503.png)

I intentionally tried to avoid looking at file extensions due to complications and potential conflicts with other extensions. Instead, I choose to rely on having other extensions make the associations and just use the Language IDs registered to figure out which type of files to lint. 

For instance, if you work with `.erb` files, presumably you're using another extension like [Simple Ruby ERB](https://github.com/vortizhe/vscode-ruby-erb) to highlight and lint the eRuby language. That extension adds [ruby](https://github.com/vortizhe/vscode-ruby-erb/blob/6fd8eb73b88e168145814b305d4e43cda16043e5/package.json#L31) and [erb](https://github.com/vortizhe/vscode-ruby-erb/blob/6fd8eb73b88e168145814b305d4e43cda16043e5/package.json#L36) language ids with the appropriate associations to file extension. In that case, you would add `ruby` and `erb` to the list of Language IDs to treat as plaintext to get the linter to automatically spell / grammar check. 

Does this make sense, or did I miss something?

**Comment by lawrencegripper** [comment]
Nope that makes perfect sense! Sorry, I missed that setting it looks like exactly what I want 👍
