### ISSUE TITLE
Words in backticks seem to be invisible to the linter

### ISSUE THREAD

**Issue by looeee** [davidlday/vscode-languagetool-linter#40]
When I use backticks for inline code, which I think is standard markdown, the linter fails to see the word. Here I get a THE_SENT_END error :

```
...such as a `Mesh`.
```
With the message: **Did you forget something after 'a'?**

**Comment by davidlday** [comment]
I think this'll need fixed in a dependency. I have a busy week but will see what I can figure out by the weekend. Thanks!

**Comment by davidlday** [comment]
@looee - I think I have a fix. The side effect is that LanguageTool will check everything inside the ticks as if it were natural language.

I can implement to only check inline code, which probably isn't too disruptive. Or I can implement for both inline code and code blocks. Checking code blocks feels like it would be intrusive since `code` isn't natural language.

What do you think? Check both inline code and code blocks, or just inline code?

**Comment by looeee** [comment]
Checking code blocks will lead to lots of fake error noise, so I would say just inline code is better.

**Comment by davidlday** [comment]
@looeee - I have a fix where LanguageTool ignores all the text between the backticks for inline code. Will be publishing a new version soon with the fix.

**Comment by looeee** [comment]
That's great! Thank you so much for the speedy response 👍

**Comment by davidlday** [comment]
Version 0.4.0 broke when published. Reverted to 0.3.2 and will implement when I figure out what happened.

**Comment by davidlday** [comment]
Fixed in 0.5.0
