### ISSUE TITLE
Allow to setup a port for managed service

### ISSUE THREAD

**Issue by jseto** [davidlday/vscode-languagetool-linter#78]
The _Managed Service_ always try to find _Language Tool_ in port 8000. This can lead to some conflicts with other servers, specially developing servers, as it is a popular port.

It will be nice to be able to set up the port in the _Managed Service_.

**Comment by davidlday** [comment]
The way it works now, the Managed Service picks an open port starting at port 8000, but if the port's in use already, it will move on to 8001, incrementally testing ports until it finds one available. I'm trying to avoid a lot of manual configuration on the Managed Service. Knowing that the ports are tested and picked automatically, do you still see a need for setting ports? I could be convinced to add options for minimum and maximum ports, but I'm still inclined to let the extension pick which port it uses based on port availability.

**Comment by jseto** [comment]
I saw that it changes port but it behaves erratically. Despite that I agree with you about minimum configuration, I don't think iterating to find an open port it's a good idea because of the following reasons:

- Not having a fixed port lets the system in uncertain and variable state, which is not good to track errors and erratic behaviour.

- Let's say vsCode is started first. In such a situation, LanguageTool Linter will peek port 8000. After that, I open my dev server at port 8000. It will fail. Setting everything to a fixed port will avoid such cases.

The ability to set up a range of ports will solve the last problem as well. I will suggest the possibility to be able to set a range in the form of `xxxx-yyyy` and a fixed port as `zzzz` in the same setting.

**Comment by davidlday** [comment]
Been thinking on this a little more. I can add a min and max, and if they're the same, then that effectively locks the port number.

But the problem I was trying to avoid in the first place comes from opening multiple vscode windows / workspaces. Each new window operates independently, and will try to start its own managed service. I used Atom for the longest time, and saw this problem with the Atom's LanguageTool extension . 

The problem goes like this:

1. The user specifies that the managed service only runs on port 8000.
1. Open vscode window A, which starts a managed service on port 8000.
1. Open vscode window B. B tries to start a managed service on port 8000 but fails since window A already has a service running on that port.
1. Both window A and window B appear to be working because they're both using the managed service on port 8000. However, window A owns the underlying process.
1. Close window A, stopping the managed service on port 8000.
1. Window B now appears broken because the managed service on port 8000 is no longer available.

Having a range of ports allows multiple windows to have their own instance of the service running and not interfere with each other, although the trade off is memory consumption.

It's probably addressable in other ways, but I wind up writing a lot of code to manage the service instead of writing code to integrate the service into vscode. This is, in part, why I strongly advocate running LanguageTool outside of vscode and just pointing to that service's URL, which is what I do.

Any thoughts on the scenario above? I don't want users confused by suddenly having the underlying service stop.

**Comment by jseto** [comment]
You are right. I didn't think about the process ownership. So your proposal of having a configurable address pool is the easiest, quickest and safest to implement.

Anyway, as a low priority improvement, you can keep the idea about only 1 port. For example, as an idea to explore, checking for response every time the service is requested and if not, start the service again. I understand that this might not be trivial as have to deal with many other reasons why the service is not responding.

**Comment by davidlday** [comment]
I'll add min and max port options, and to address the possibility of conflict using defaults, I'll set the defaults to a higher range. Any suggestions on a good starting min? Would 9000 be high enough?

**Comment by jseto** [comment]
I don't know any local service that typically uses port 9000 but a quick research on the internet shows that round numbers are used by several local services. In particular, I found this [page](https://localhosts.mobi/:9000) which states that port 9000 is used by _Windows_ virtual networks. I don't know to which extent this is used or how popular is it.

My googling research shows that port 9500 is not used. Therefore, it may be a good start.
